[0m21:40:00.645438 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1063f0050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10763fd90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10763fc50>]}


============================== 21:40:00.647942 | b8f48311-c0ba-4b11-9388-848e9ffba59a ==============================
[0m21:40:00.647942 [info ] [MainThread]: Running with dbt=1.9.3
[0m21:40:00.648246 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': '/Users/chaimturkel/.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt deps', 'send_anonymous_usage_stats': 'True'}
[0m21:40:00.648645 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/chaimturkel/workspace/tikal/cne/cne-dagster-template/cne_dagster/cne_dagster/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:40:00.648939 [debug] [MainThread]: Resource report: {"command_name": "deps", "command_success": false, "command_wall_clock_time": 0.0342925, "process_in_blocks": "0", "process_kernel_time": 0.096947, "process_mem_max_rss": "98844672", "process_out_blocks": "0", "process_user_time": 0.533108}
[0m21:40:00.649139 [debug] [MainThread]: Command `dbt deps` failed at 21:40:00.649100 after 0.03 seconds
[0m21:40:00.649297 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10765e650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107575c70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10755aad0>]}
[0m21:40:00.649435 [debug] [MainThread]: Flushing usage events
[0m21:40:01.259159 [debug] [MainThread]: An error was encountered while trying to flush usage events
