[0m21:39:49.856017 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1052f0050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10663fd90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10663fc50>]}


============================== 21:39:49.858354 | 255744f4-a097-4363-9210-64d794bfe47d ==============================
[0m21:39:49.858354 [info ] [MainThread]: Running with dbt=1.9.3
[0m21:39:49.858645 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/Users/chaimturkel/.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt deps', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m21:39:49.859049 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/chaimturkel/workspace/tikal/cne/cne-dagster-template/cne_dagster/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:39:49.859347 [debug] [MainThread]: Resource report: {"command_name": "deps", "command_success": false, "command_wall_clock_time": 0.036681417, "process_in_blocks": "0", "process_kernel_time": 0.086982, "process_mem_max_rss": "97779712", "process_out_blocks": "0", "process_user_time": 0.518362}
[0m21:39:49.859538 [debug] [MainThread]: Command `dbt deps` failed at 21:39:49.859501 after 0.04 seconds
[0m21:39:49.859690 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10665e650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106575c70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10655aad0>]}
[0m21:39:49.859834 [debug] [MainThread]: Flushing usage events
[0m21:39:50.754666 [debug] [MainThread]: An error was encountered while trying to flush usage events
